### ISSUE TITLE
package.json/main refers to tasks/grunt-vows.js which does not exist

### ISSUE THREAD

**Issue by silkentrance** [CMTegner/grunt-vows#15]
Please make this

    "main" : "tasks/vows.js"

instead.

**Comment by CMTegner** [comment]
Hi!

First of all: thanks for taking the time to create an issue! Second: I could spend time explaining how busy things have been lately, but I'm sure you're much more interested in me fixing the problem than making excuses for myself.

`0.4.2` should fix both problems you reported. Let me know if you run into any more issues!

**Comment by silkentrance** [comment]
@CMTegner Hey, thanks for fixing this. Great.
